#define phones 3
#define cashiers 2
#define seats_per_row 10
#define front_rows 10
#define back_rows 20
#define pinA 30
#define costA 30
#define costB 20
#define seatLow 1
#define seatHigh 5
#define resLow 1
#define resHigh 5
#define tSlow 5
#define tHigh 13
#define cashLow 4
#define cashHigh 8
#define success_rate 90
